#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_AV_Default_SurvivorCharmsChains

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "enum_charmsJointAttachment_structs.hpp"
#include "enum_charmsJointChains_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass AB_AV_Default_SurvivorCharmsChains.AB_AV_Default_SurvivorCharmsChains_C
// 0x0480 (0x07F0 - 0x0370)
class UAB_AV_Default_SurvivorCharmsChains_C final : public UAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0378(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0380(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0388(0x0020)()
	struct FAnimNode_CopyPoseFromMesh             AnimGraphNode_CopyPoseFromMesh;                    // 0x03A8(0x0158)(ContainsInstancedReference)
	struct FAnimNode_LinkedAnimGraph              AnimGraphNode_LinkedAnimGraph_2;                   // 0x0500(0x00B8)()
	struct FAnimNode_LinkedAnimGraph              AnimGraphNode_LinkedAnimGraph_1;                   // 0x05B8(0x00B8)()
	struct FAnimNode_LinkedAnimGraph              AnimGraphNode_LinkedAnimGraph;                     // 0x0670(0x00B8)()
	Enum_CharmsJointChains                        __CustomProperty_JointChain_CB76ADD6424CB92F8744F88F78B38AEA; // 0x0728(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_729[0x7];                                      // 0x0729(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               __CustomProperty_RotationOffset_CB76ADD6424CB92F8744F88F78B38AEA; // 0x0730(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                __CustomProperty_TranslationOffset_CB76ADD6424CB92F8744F88F78B38AEA; // 0x0748(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_CharmsJointAttachment                    __CustomProperty_ConstraintParent_CB76ADD6424CB92F8744F88F78B38AEA; // 0x0760(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_CharmsJointChains                        __CustomProperty_JointChain_2CE95C6D4DA91A275E7C6EA7DFA6D52B; // 0x0761(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_762[0x6];                                      // 0x0762(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               __CustomProperty_RotationOffset_2CE95C6D4DA91A275E7C6EA7DFA6D52B; // 0x0768(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                __CustomProperty_TranslationOffset_2CE95C6D4DA91A275E7C6EA7DFA6D52B; // 0x0780(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_CharmsJointAttachment                    __CustomProperty_ConstraintParent_2CE95C6D4DA91A275E7C6EA7DFA6D52B; // 0x0798(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_CharmsJointChains                        __CustomProperty_JointChain_D927FE79478D98C5FC4FE69FF67F515D; // 0x0799(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_79A[0x6];                                      // 0x079A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               __CustomProperty_RotationOffset_D927FE79478D98C5FC4FE69FF67F515D; // 0x07A0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                __CustomProperty_TranslationOffset_D927FE79478D98C5FC4FE69FF67F515D; // 0x07B8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_CharmsJointAttachment                    __CustomProperty_ConstraintParent_D927FE79478D98C5FC4FE69FF67F515D; // 0x07D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7D1[0x7];                                      // 0x07D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ACharmAttacher*                         CharmAttacher;                                     // 0x07D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 OwningSkeletalMesh;                                // 0x07E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void BlueprintLinkedAnimationLayersInitialized();
	void ExecuteUbergraph_AB_AV_Default_SurvivorCharmsChains(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AB_AV_Default_SurvivorCharmsChains_C">();
	}
	static class UAB_AV_Default_SurvivorCharmsChains_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAB_AV_Default_SurvivorCharmsChains_C>();
	}
};
static_assert(alignof(UAB_AV_Default_SurvivorCharmsChains_C) == 0x000010, "Wrong alignment on UAB_AV_Default_SurvivorCharmsChains_C");
static_assert(sizeof(UAB_AV_Default_SurvivorCharmsChains_C) == 0x0007F0, "Wrong size on UAB_AV_Default_SurvivorCharmsChains_C");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, UberGraphFrame) == 0x000370, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, AnimBlueprintExtension_PropertyAccess) == 0x000378, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, AnimBlueprintExtension_Base) == 0x000380, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, AnimGraphNode_Root) == 0x000388, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, AnimGraphNode_CopyPoseFromMesh) == 0x0003A8, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::AnimGraphNode_CopyPoseFromMesh' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, AnimGraphNode_LinkedAnimGraph_2) == 0x000500, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::AnimGraphNode_LinkedAnimGraph_2' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, AnimGraphNode_LinkedAnimGraph_1) == 0x0005B8, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::AnimGraphNode_LinkedAnimGraph_1' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, AnimGraphNode_LinkedAnimGraph) == 0x000670, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::AnimGraphNode_LinkedAnimGraph' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, __CustomProperty_JointChain_CB76ADD6424CB92F8744F88F78B38AEA) == 0x000728, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::__CustomProperty_JointChain_CB76ADD6424CB92F8744F88F78B38AEA' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, __CustomProperty_RotationOffset_CB76ADD6424CB92F8744F88F78B38AEA) == 0x000730, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::__CustomProperty_RotationOffset_CB76ADD6424CB92F8744F88F78B38AEA' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, __CustomProperty_TranslationOffset_CB76ADD6424CB92F8744F88F78B38AEA) == 0x000748, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::__CustomProperty_TranslationOffset_CB76ADD6424CB92F8744F88F78B38AEA' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, __CustomProperty_ConstraintParent_CB76ADD6424CB92F8744F88F78B38AEA) == 0x000760, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::__CustomProperty_ConstraintParent_CB76ADD6424CB92F8744F88F78B38AEA' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, __CustomProperty_JointChain_2CE95C6D4DA91A275E7C6EA7DFA6D52B) == 0x000761, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::__CustomProperty_JointChain_2CE95C6D4DA91A275E7C6EA7DFA6D52B' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, __CustomProperty_RotationOffset_2CE95C6D4DA91A275E7C6EA7DFA6D52B) == 0x000768, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::__CustomProperty_RotationOffset_2CE95C6D4DA91A275E7C6EA7DFA6D52B' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, __CustomProperty_TranslationOffset_2CE95C6D4DA91A275E7C6EA7DFA6D52B) == 0x000780, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::__CustomProperty_TranslationOffset_2CE95C6D4DA91A275E7C6EA7DFA6D52B' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, __CustomProperty_ConstraintParent_2CE95C6D4DA91A275E7C6EA7DFA6D52B) == 0x000798, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::__CustomProperty_ConstraintParent_2CE95C6D4DA91A275E7C6EA7DFA6D52B' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, __CustomProperty_JointChain_D927FE79478D98C5FC4FE69FF67F515D) == 0x000799, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::__CustomProperty_JointChain_D927FE79478D98C5FC4FE69FF67F515D' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, __CustomProperty_RotationOffset_D927FE79478D98C5FC4FE69FF67F515D) == 0x0007A0, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::__CustomProperty_RotationOffset_D927FE79478D98C5FC4FE69FF67F515D' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, __CustomProperty_TranslationOffset_D927FE79478D98C5FC4FE69FF67F515D) == 0x0007B8, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::__CustomProperty_TranslationOffset_D927FE79478D98C5FC4FE69FF67F515D' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, __CustomProperty_ConstraintParent_D927FE79478D98C5FC4FE69FF67F515D) == 0x0007D0, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::__CustomProperty_ConstraintParent_D927FE79478D98C5FC4FE69FF67F515D' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, CharmAttacher) == 0x0007D8, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::CharmAttacher' has a wrong offset!");
static_assert(offsetof(UAB_AV_Default_SurvivorCharmsChains_C, OwningSkeletalMesh) == 0x0007E0, "Member 'UAB_AV_Default_SurvivorCharmsChains_C::OwningSkeletalMesh' has a wrong offset!");

}

