#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CamperTakenByEntity

#include "Basic.hpp"

#include "DeadByDaylight_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CamperTakenByEntity.BP_CamperTakenByEntity_C
// 0x0018 (0x0100 - 0x00E8)
class UBP_CamperTakenByEntity_C final : public UDBD_CrossDissolver
{
public:
	class UCurveFloat*                            DissolveSpeed;                                     // 0x00E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<class UMaterialInterface*>             SurvivorMaterials;                                 // 0x00F0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void TransitionProgress(double Time);
	void MakeBaseMaterialsDynamic();
	void DoTransitionUpdate(double Time);
	void DoTransitionEnd(TArray<class UDBDClipRegionComponent*>& Hook_Clip_Regions);
	void DoTransitionBegin(TArray<class UDBDClipRegionComponent*>& Hook_Clip_Region);
	void AssignSacrificeMaterialToClone(TArray<class UDBDClipRegionComponent*>& HookClipRegions);
	void AssignSacrificeMaterialToBase(TArray<class UDBDClipRegionComponent*>& Hook_Regions);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CamperTakenByEntity_C">();
	}
	static class UBP_CamperTakenByEntity_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CamperTakenByEntity_C>();
	}
};
static_assert(alignof(UBP_CamperTakenByEntity_C) == 0x000008, "Wrong alignment on UBP_CamperTakenByEntity_C");
static_assert(sizeof(UBP_CamperTakenByEntity_C) == 0x000100, "Wrong size on UBP_CamperTakenByEntity_C");
static_assert(offsetof(UBP_CamperTakenByEntity_C, DissolveSpeed) == 0x0000E8, "Member 'UBP_CamperTakenByEntity_C::DissolveSpeed' has a wrong offset!");
static_assert(offsetof(UBP_CamperTakenByEntity_C, SurvivorMaterials) == 0x0000F0, "Member 'UBP_CamperTakenByEntity_C::SurvivorMaterials' has a wrong offset!");

}

